"""Doc-versus-CSV agreement guard for the M3-02 German EPA deliverable
(`docs/epa-refinement-2026-10.md`).

This guard exists so that a number in the coach-facing document can never
drift away from the measured CSV it claims to report -- if a figure in
`docs/epa-refinement-2026-10.md` is wrong, the fix is a re-measurement
(re-run the relevant `scripts/*.py`), never a prose edit. Every MLflow run
id and every log-loss figure quoted in a structured table in the document
is checked against `data/reference/epa_refinement/*.csv` in both
directions: the document may not cite a run the CSV does not have, and the
CSV may not have a run the document silently omits.

Only the document's STRUCTURED tables (the ones with an explicit "Run-ID"
or per-source "Verbesserung" header) are figure-checked -- free prose
(e.g. the Phase-1.3 historical comparison numbers, which are legitimately
NOT in this phase's `data/reference/epa_refinement/*.csv`) is out of
scope for the figure guard, matching this plan's own instruction not to
assert on wording/tone/ordering beyond what Task 1's own verify already
gates. `tests/test_m3_epa_snapshot.py` (M3-02-03) already guards
`data/reference/hc_sp_tables/*.csv` itself; this file does not duplicate
those assertions.

Mostly stdlib + pytest, no network, sub-second -- with one exception (M3-05-02): the
MODELLKARTE guard below additionally resolves run ids/figures against the real, local
`mlruns/mlflow.db` store when it exists (`mlruns/` is gitignored, never committed -- see
`.gitignore`), since `docs/epa-modellkarte.md` is now generated by
`scripts/render_model_card.py` from the LIVE champion run, which does not necessarily have a
row in any `data/reference/epa_refinement/*/ablation_summary.csv` (the current production
champion predates the ablation work entirely). Those checks `pytest.skip` gracefully when the
local store is absent (CI, a fresh checkout) -- exactly this file's existing skip-on-missing
convention, just applied to a live store instead of a committed CSV.

Stdlib + pytest only, no network, sub-second.
"""

from __future__ import annotations

import csv
import re
import sys
from datetime import date
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

DOC = REPO_ROOT / "docs" / "epa-refinement-2026-10.md"
RUECKFRAGEN = REPO_ROOT / "docs" / "hc-rueckfragen-2026-09.md"
MODELLKARTE = REPO_ROOT / "docs" / "epa-modellkarte.md"
ROSTER = REPO_ROOT / "data" / "reference" / "roster.csv"
EPA_DIR = REPO_ROOT / "data" / "reference" / "epa_refinement"
ABLATION_CSV = EPA_DIR / "ablation_summary.csv"
PER_SOURCE_EP_CSV = EPA_DIR / "per_source_metrics_ep.csv"
PER_SOURCE_WP_CSV = EPA_DIR / "per_source_metrics_wp.csv"

# 2026-09-08 re-measurement (post-IFAF-correction) -- a dated subfolder, never overwriting
# the 2026-09-04 CSVs above so the reviewed, freigegeben document stays byte-reproducible.
# See "## Nachtrag: Stand 2026-09-08" in DOC.
RERUN_DIR = EPA_DIR / "2026-09-08"
RERUN_ABLATION_CSV = RERUN_DIR / "ablation_summary.csv"
RERUN_PER_SOURCE_EP_CSV = RERUN_DIR / "per_source_metrics_ep.csv"
RERUN_PER_SOURCE_WP_CSV = RERUN_DIR / "per_source_metrics_wp.csv"
NACHTRAG_SECTION_MARKER = "## Nachtrag: Stand 2026-09-08"

# M3-05-07: the extra-point training-leak fix, measured as its own dated methodology-change
# section -- a dated subfolder like RERUN_DIR above, never overwriting the 2026-09-08 CSVs.
# See "## Methodenaenderung: Extrapunkt-Ausschluss" in DOC.
EXTRA_POINT_FIX_DIR = EPA_DIR / "2026-09-09"
EXTRA_POINT_FIX_ABLATION_CSV = EXTRA_POINT_FIX_DIR / "ablation_summary.csv"
EXTRA_POINT_SECTION_MARKER = "## Methodenaenderung: Extrapunkt-Ausschluss"

_RUN_ID_RE = re.compile(r"\b[0-9a-f]{32}\b")
_MIN_SURNAME_LEN = 6


def _read(path: Path) -> str:
    if not path.exists():
        pytest.skip(f"{path} does not exist")
    return path.read_text(encoding="utf-8")


def _csv_rows(path: Path) -> list[dict]:
    if not path.exists():
        pytest.skip(f"{path} does not exist -- run the M3-02 measurement scripts first")
    with path.open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def _run_ids_in_text(text: str) -> set[str]:
    return set(_RUN_ID_RE.findall(text))


def _find_table(text: str, header_marker: str) -> list[list[str]]:
    """Return every row (header first) of the first Markdown table whose
    header line contains `header_marker`, as a list of stripped cells."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("|") and header_marker in stripped:
            start = i
            break
    assert start is not None, f"no table found with header marker {header_marker!r}"

    rows: list[list[str]] = []
    for line in lines[start:]:
        stripped = line.strip()
        if not stripped.startswith("|"):
            break
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if all(re.fullmatch(r":?-+:?", c) for c in cells):
            continue  # markdown header-separator row (incl. alignment colons)
        rows.append(cells)
    return rows


def _to_float(cell: str) -> float:
    """Parse a written figure, tolerant of German decimal comma AND point.
    Strips surrounding backticks/whitespace first."""
    cleaned = cell.strip().strip("`")
    return float(cleaned.replace(",", "."))


def _written_decimals(cell: str) -> int:
    cleaned = cell.strip().strip("`")
    sep = "," if "," in cleaned else ("." if "." in cleaned else None)
    if sep is None:
        return 0
    return len(cleaned.split(sep)[-1])


def _assert_figure_matches(written: str, measured: float, label: str) -> None:
    """Tolerance is derived from the precision the document actually wrote,
    not a fixed epsilon -- a figure written as `1,03` (2 decimals) must
    match a measured `1.027657` (tolerance 0.005), while a figure written
    at full precision (`0,957593`) must match to within half a
    millionth."""
    written_value = _to_float(written)
    decimals = _written_decimals(written)
    tolerance = 0.5 * (10 ** (-decimals)) if decimals else 0.5
    assert abs(written_value - measured) <= tolerance, (
        f"{label}: document says {written!r} ({written_value}), measured CSV value is "
        f"{measured} -- outside tolerance {tolerance} for {decimals} written decimals"
    )


def _load_roster_names() -> tuple[set[str], set[str]]:
    """`(full_names, long_surnames)` from `roster.csv`, same shape/skip
    behaviour as `tests/test_m3_epa_snapshot.py::_load_roster_names`."""
    if not ROSTER.exists():
        pytest.skip(f"{ROSTER} does not exist -- cannot run the PII gate")
    with ROSTER.open(encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    full_names = {row["player_name"].strip() for row in rows if row.get("player_name")}
    if not full_names:
        pytest.skip("roster.csv produced zero player names -- loader broken?")

    surnames: set[str] = set()
    for name in full_names:
        parts = name.split()
        if not parts:
            continue
        surname = parts[-1]
        if len(surname) >= _MIN_SURNAME_LEN:
            surnames.add(surname)
    return full_names, surnames


# ---------------------------------------------------------------------------
# Run-id agreement (bidirectional)
# ---------------------------------------------------------------------------


def test_run_ids_match_ablation_summary_bidirectionally() -> None:
    """Scoped to the main (2026-09-04) report only -- everything in the document up to
    `NACHTRAG_SECTION_MARKER`. The 2026-09-08 Nachtrag cites four different run ids from a
    different CSV (`RERUN_ABLATION_CSV`), checked separately by
    `test_rerun_run_ids_match_rerun_ablation_summary_bidirectionally` below -- a single
    document-wide scan would incorrectly flag either section's run ids as "extra" relative
    to the other section's CSV.
    """
    doc_text = _read(DOC)
    main_report_text = doc_text.split(NACHTRAG_SECTION_MARKER, 1)[0]
    ablation_rows = _csv_rows(ABLATION_CSV)

    doc_run_ids = _run_ids_in_text(main_report_text)
    csv_run_ids = {row["run_id"] for row in ablation_rows}

    missing_from_doc = csv_run_ids - doc_run_ids
    extra_in_doc = doc_run_ids - csv_run_ids

    assert not missing_from_doc, (
        f"ablation_summary.csv has run id(s) never quoted in {DOC.name}: {missing_from_doc}"
    )
    assert not extra_in_doc, (
        f"{DOC.name} quotes run id(s) not present in ablation_summary.csv: {extra_in_doc}"
    )


def test_rerun_run_ids_match_rerun_ablation_summary_bidirectionally() -> None:
    """The 2026-09-08 Nachtrag section's own run-id agreement check, mirroring
    `test_run_ids_match_ablation_summary_bidirectionally` but scoped to
    `NACHTRAG_SECTION_MARKER` onward and `RERUN_ABLATION_CSV`.

    Bounded at `EXTRA_POINT_SECTION_MARKER` (via `_nachtrag_text()`, M3-05-07) so the later
    dated methodology-change section's own, different run ids are never counted as "extra"
    here -- mirrors this exact re-scoping pattern's own precedent
    (`test_run_ids_match_ablation_summary_bidirectionally` was re-scoped the same way when
    the 2026-09-08 Nachtrag was first added).
    """
    nachtrag_text = _nachtrag_text()
    ablation_rows = _csv_rows(RERUN_ABLATION_CSV)

    doc_run_ids = _run_ids_in_text(nachtrag_text)
    csv_run_ids = {row["run_id"] for row in ablation_rows}

    missing_from_doc = csv_run_ids - doc_run_ids
    extra_in_doc = doc_run_ids - csv_run_ids

    assert not missing_from_doc, (
        f"{RERUN_ABLATION_CSV} has run id(s) never quoted in the Nachtrag: {missing_from_doc}"
    )
    assert not extra_in_doc, (
        f"the Nachtrag quotes run id(s) not present in {RERUN_ABLATION_CSV}: {extra_in_doc}"
    )


# ---------------------------------------------------------------------------
# Log-loss figure agreement (structured tables only)
# ---------------------------------------------------------------------------


def test_ablation_table_figures_match_ablation_summary_csv() -> None:
    doc_text = _read(DOC)
    ablation_rows = _csv_rows(ABLATION_CSV)
    by_run_id = {row["run_id"]: row for row in ablation_rows}

    rows = _find_table(doc_text, "Naive Grundrate")
    header, data_rows = rows[0], rows[1:]
    assert len(header) == 8, f"unexpected ablation table header shape: {header}"

    checked = 0
    for cells in data_rows:
        _, _, _, _, metric_cell, naive_cell, impr_cell, run_id_cell = cells
        run_id = run_id_cell.strip("`")
        assert run_id in by_run_id, f"run id {run_id!r} in doc table has no ablation_summary.csv row"
        csv_row = by_run_id[run_id]

        _assert_figure_matches(metric_cell, float(csv_row["metric_value"]), f"{run_id} metric_value")
        _assert_figure_matches(naive_cell, float(csv_row["naive_value"]), f"{run_id} naive_value")
        _assert_figure_matches(
            impr_cell, float(csv_row["logloss_improvement"]), f"{run_id} logloss_improvement"
        )
        checked += 1

    assert checked == len(ablation_rows), (
        f"expected {len(ablation_rows)} ablation rows checked, got {checked}"
    )


def test_per_source_table_figures_match_per_source_csvs() -> None:
    doc_text = _read(DOC)
    ep_rows = {
        row["source"]: row for row in _csv_rows(PER_SOURCE_EP_CSV) if row["arm"] == "with_hc"
    }
    wp_rows = {
        row["source"]: row for row in _csv_rows(PER_SOURCE_WP_CSV) if row["arm"] == "with_hc"
    }

    rows = _find_table(doc_text, "EP Verbesserung")
    header, data_rows = rows[0], rows[1:]
    assert len(header) == 9, f"unexpected per-source table header shape: {header}"

    assert data_rows, "per-source comparison table has no data rows"
    for cells in data_rows:
        source_cell, _, ep_ll, ep_naive, ep_impr, _, wp_ll, wp_naive, wp_impr = cells
        source = source_cell.strip("`")

        assert source in ep_rows, f"source {source!r} in doc table has no per_source_metrics_ep.csv row"
        assert source in wp_rows, f"source {source!r} in doc table has no per_source_metrics_wp.csv row"

        ep_row, wp_row = ep_rows[source], wp_rows[source]
        _assert_figure_matches(ep_ll, float(ep_row["logloss"]), f"{source} EP logloss")
        _assert_figure_matches(ep_naive, float(ep_row["naive_logloss"]), f"{source} EP naive")
        _assert_figure_matches(ep_impr, float(ep_row["improvement"]), f"{source} EP improvement")
        _assert_figure_matches(wp_ll, float(wp_row["logloss"]), f"{source} WP logloss")
        _assert_figure_matches(wp_naive, float(wp_row["naive_logloss"]), f"{source} WP naive")
        _assert_figure_matches(wp_impr, float(wp_row["improvement"]), f"{source} WP improvement")


# ---------------------------------------------------------------------------
# 2026-09-08 Nachtrag: figure agreement against the rerun CSVs
# ---------------------------------------------------------------------------


def _nachtrag_text() -> str:
    """The 2026-09-08 Nachtrag section only -- bounded at `EXTRA_POINT_SECTION_MARKER`
    (M3-05-07) when present, so that later dated section's own run ids/figures are never
    swept into this section's checks. Without this bound, a whole-document-to-EOF scan would
    incorrectly flag the M3-05-07 section's disjoint run ids as "extra" relative to
    `RERUN_ABLATION_CSV` -- the exact failure mode this helper's own docstring precedent
    (see `test_run_ids_match_ablation_summary_bidirectionally`) already warns about."""
    doc_text = _read(DOC)
    assert NACHTRAG_SECTION_MARKER in doc_text, f"{DOC.name} has no {NACHTRAG_SECTION_MARKER!r} section"
    nachtrag_onward = doc_text.split(NACHTRAG_SECTION_MARKER, 1)[1]
    if EXTRA_POINT_SECTION_MARKER in nachtrag_onward:
        nachtrag_onward = nachtrag_onward.split(EXTRA_POINT_SECTION_MARKER, 1)[0]
    return nachtrag_onward


def _extra_point_fix_text() -> str:
    """M3-05-07's dated methodology-change section -- everything from
    `EXTRA_POINT_SECTION_MARKER` to the end of the document."""
    doc_text = _read(DOC)
    assert EXTRA_POINT_SECTION_MARKER in doc_text, (
        f"{DOC.name} has no {EXTRA_POINT_SECTION_MARKER!r} section"
    )
    return doc_text.split(EXTRA_POINT_SECTION_MARKER, 1)[1]


def test_rerun_ablation_table_figures_match_rerun_ablation_summary_csv() -> None:
    nachtrag_text = _nachtrag_text()
    ablation_rows = _csv_rows(RERUN_ABLATION_CSV)
    by_run_id = {row["run_id"]: row for row in ablation_rows}

    rows = _find_table(nachtrag_text, "Naive Grundrate")
    header, data_rows = rows[0], rows[1:]
    assert len(header) == 8, f"unexpected rerun ablation table header shape: {header}"

    checked = 0
    for cells in data_rows:
        _, _, _, _, metric_cell, naive_cell, impr_cell, run_id_cell = cells
        run_id = run_id_cell.strip("`")
        assert run_id in by_run_id, f"run id {run_id!r} in Nachtrag table has no {RERUN_ABLATION_CSV} row"
        csv_row = by_run_id[run_id]

        _assert_figure_matches(metric_cell, float(csv_row["metric_value"]), f"{run_id} metric_value")
        _assert_figure_matches(naive_cell, float(csv_row["naive_value"]), f"{run_id} naive_value")
        _assert_figure_matches(
            impr_cell, float(csv_row["logloss_improvement"]), f"{run_id} logloss_improvement"
        )
        checked += 1

    assert checked == len(ablation_rows), (
        f"expected {len(ablation_rows)} rerun ablation rows checked, got {checked}"
    )


def test_rerun_per_source_table_figures_match_rerun_per_source_csvs() -> None:
    nachtrag_text = _nachtrag_text()
    ep_rows = {
        row["source"]: row for row in _csv_rows(RERUN_PER_SOURCE_EP_CSV) if row["arm"] == "with_hc"
    }
    wp_rows = {
        row["source"]: row for row in _csv_rows(RERUN_PER_SOURCE_WP_CSV) if row["arm"] == "with_hc"
    }

    rows = _find_table(nachtrag_text, "EP Verbesserung")
    header, data_rows = rows[0], rows[1:]
    assert len(header) == 9, f"unexpected rerun per-source table header shape: {header}"

    assert data_rows, "rerun per-source comparison table has no data rows"
    for cells in data_rows:
        source_cell, _, ep_ll, ep_naive, ep_impr, _, wp_ll, wp_naive, wp_impr = cells
        source = source_cell.strip("`")

        assert source in ep_rows, f"source {source!r} in Nachtrag table has no rerun EP CSV row"
        assert source in wp_rows, f"source {source!r} in Nachtrag table has no rerun WP CSV row"

        ep_row, wp_row = ep_rows[source], wp_rows[source]
        _assert_figure_matches(ep_ll, float(ep_row["logloss"]), f"{source} rerun EP logloss")
        _assert_figure_matches(ep_naive, float(ep_row["naive_logloss"]), f"{source} rerun EP naive")
        _assert_figure_matches(ep_impr, float(ep_row["improvement"]), f"{source} rerun EP improvement")
        _assert_figure_matches(wp_ll, float(wp_row["logloss"]), f"{source} rerun WP logloss")
        _assert_figure_matches(wp_naive, float(wp_row["naive_logloss"]), f"{source} rerun WP naive")
        _assert_figure_matches(wp_impr, float(wp_row["improvement"]), f"{source} rerun WP improvement")


def test_nachtrag_records_corpus_fingerprint_and_git_commit() -> None:
    """Task-1 requirement: every rerun MLflow param set includes `corpus_fingerprint` and
    `git_commit` (`scripts/hc_corpus_ablation.py::run_arm`) -- this test checks the
    human-facing side of that: the exact same values are quoted in the Nachtrag prose, not
    just buried in the CSV/MLflow store."""
    nachtrag_text = _nachtrag_text()
    ablation_rows = _csv_rows(RERUN_ABLATION_CSV)
    assert ablation_rows, f"{RERUN_ABLATION_CSV} has no rows"

    fingerprints = {row["corpus_fingerprint"] for row in ablation_rows}
    commits = {row["git_commit"] for row in ablation_rows}
    assert len(fingerprints) == 1, f"expected one shared corpus_fingerprint across all arms, got {fingerprints}"
    assert len(commits) == 1, f"expected one shared git_commit across all arms, got {commits}"

    (fingerprint,) = fingerprints
    (commit,) = commits
    assert fingerprint and fingerprint != "unknown", "corpus_fingerprint missing/empty in rerun CSV"
    assert commit and commit != "unknown", "git_commit missing/empty in rerun CSV"
    assert fingerprint in nachtrag_text, f"corpus_fingerprint {fingerprint!r} not quoted in the Nachtrag"
    assert commit in nachtrag_text, f"git_commit {commit!r} not quoted in the Nachtrag"


# ---------------------------------------------------------------------------
# M3-05-07: extra-point training-leak fix, dated methodology-change section
# ---------------------------------------------------------------------------


def test_extra_point_fix_run_ids_match_ablation_summary_bidirectionally() -> None:
    """M3-05-07's dated section's own run-id agreement check, mirroring
    `test_rerun_run_ids_match_rerun_ablation_summary_bidirectionally` but scoped to
    `EXTRA_POINT_SECTION_MARKER` onward and `EXTRA_POINT_FIX_ABLATION_CSV`.

    The section deliberately does NOT re-quote the pre-existing champion's run ids as literal
    hex strings (same precedent as the `## Champion-Entscheidung` section) -- they are not in
    `EXTRA_POINT_FIX_ABLATION_CSV` (neither candidate was promoted), so quoting them here
    would fail this exact check.
    """
    section_text = _extra_point_fix_text()
    ablation_rows = _csv_rows(EXTRA_POINT_FIX_ABLATION_CSV)

    doc_run_ids = _run_ids_in_text(section_text)
    csv_run_ids = {row["run_id"] for row in ablation_rows}

    missing_from_doc = csv_run_ids - doc_run_ids
    extra_in_doc = doc_run_ids - csv_run_ids

    assert not missing_from_doc, (
        f"{EXTRA_POINT_FIX_ABLATION_CSV} has run id(s) never quoted in the section: {missing_from_doc}"
    )
    assert not extra_in_doc, (
        f"the section quotes run id(s) not present in {EXTRA_POINT_FIX_ABLATION_CSV}: {extra_in_doc}"
    )


def test_extra_point_fix_table_figures_match_ablation_summary_csv() -> None:
    """Mirrors `test_rerun_ablation_table_figures_match_rerun_ablation_summary_csv`, scoped
    to the M3-05-07 section's own before/after table and `EXTRA_POINT_FIX_ABLATION_CSV`."""
    section_text = _extra_point_fix_text()
    ablation_rows = _csv_rows(EXTRA_POINT_FIX_ABLATION_CSV)
    by_run_id = {row["run_id"]: row for row in ablation_rows}

    rows = _find_table(section_text, "Naive Grundrate")
    header, data_rows = rows[0], rows[1:]
    assert len(header) == 8, f"unexpected extra-point-fix ablation table header shape: {header}"

    checked = 0
    for cells in data_rows:
        _, _, _, _, metric_cell, naive_cell, impr_cell, run_id_cell = cells
        run_id = run_id_cell.strip("`")
        assert run_id in by_run_id, (
            f"run id {run_id!r} in the extra-point-fix table has no "
            f"{EXTRA_POINT_FIX_ABLATION_CSV} row"
        )
        csv_row = by_run_id[run_id]

        _assert_figure_matches(metric_cell, float(csv_row["metric_value"]), f"{run_id} metric_value")
        _assert_figure_matches(naive_cell, float(csv_row["naive_value"]), f"{run_id} naive_value")
        _assert_figure_matches(
            impr_cell, float(csv_row["logloss_improvement"]), f"{run_id} logloss_improvement"
        )
        checked += 1

    assert checked == len(ablation_rows), (
        f"expected {len(ablation_rows)} extra-point-fix ablation rows checked, got {checked}"
    )


# ---------------------------------------------------------------------------
# Every measured CSV under data/reference/epa_refinement/ is referenced
# ---------------------------------------------------------------------------


def test_document_references_every_epa_refinement_csv() -> None:
    doc_text = _read(DOC)
    if not EPA_DIR.exists():
        pytest.skip(f"{EPA_DIR} does not exist")
    csv_files = sorted(EPA_DIR.glob("*.csv"))
    assert csv_files, f"{EPA_DIR} has no committed CSVs"

    missing = [p.name for p in csv_files if p.name not in doc_text]
    assert not missing, f"{DOC.name} never names these committed CSVs: {missing}"


def test_document_references_every_rerun_csv() -> None:
    """The 2026-09-08 Nachtrag's own CSV-coverage guard, mirroring
    `test_document_references_every_epa_refinement_csv` but scoped to `RERUN_DIR` -- never
    loosens the original guard, adds an equivalent one for the dated subfolder."""
    doc_text = _read(DOC)
    if not RERUN_DIR.exists():
        pytest.skip(f"{RERUN_DIR} does not exist -- run the 2026-09-08 rerun scripts first")
    csv_files = sorted(RERUN_DIR.glob("*.csv"))
    assert csv_files, f"{RERUN_DIR} has no committed CSVs"

    missing = [f"{RERUN_DIR.name}/{p.name}" for p in csv_files if p.name not in doc_text]
    assert not missing, f"{DOC.name} never names these committed rerun CSVs: {missing}"


# ---------------------------------------------------------------------------
# MODELLKARTE (M3-05-02): generated-card run-id/figure guard
#
# docs/epa-modellkarte.md is generated by scripts/render_model_card.py from the LIVE
# champion run of ep_model/wp_model -- unlike the M3-02 sections above, its numbers are not
# guaranteed to have a row in any data/reference/epa_refinement/*/ablation_summary.csv (the
# current production champion is the original Phase-1.3 run, which predates every ablation
# CSV). Every run id it quotes must still trace back to something real: either a committed
# ablation CSV row (any dated subfolder, searched -- never hard-coded to one date) or the
# live MLflow registry itself. Figures are checked against whichever of those two sources
# actually has the run, reusing _assert_figure_matches (never a second tolerance helper).
# ---------------------------------------------------------------------------


def _all_ablation_rows() -> dict[str, dict]:
    """Every row from every `ablation_summary.csv` under EPA_DIR -- the top-level
    (2026-09-04, undated) file plus every dated subfolder (e.g. `2026-09-08/`) -- keyed by
    `run_id`. Globs rather than hard-coding one date, matching this plan's own instruction."""
    rows_by_run_id: dict[str, dict] = {}
    candidates = [ABLATION_CSV, *sorted(EPA_DIR.glob("*/ablation_summary.csv"))]
    for path in candidates:
        if not path.exists():
            continue
        with path.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                rows_by_run_id[row["run_id"]] = row
    return rows_by_run_id


def _live_mlflow_client():
    """`(config, client)` against the real repo's `ffep.toml`/`mlruns/mlflow.db`, or `None`
    if unavailable -- `mlruns/` is gitignored and never committed (verified in `.gitignore`),
    so a fresh checkout or CI runner genuinely has nothing to query here. Imports are
    function-local so a context that only needs the CSV-based checks above never pays for
    importing mlflow/flag_football_ep."""
    config_path = REPO_ROOT / "ffep.toml"
    if not config_path.exists():
        return None
    if str(REPO_ROOT / "src") not in sys.path:
        sys.path.insert(0, str(REPO_ROOT / "src"))
    from flag_football_ep.config import load_config
    from flag_football_ep.model import mlflow_store

    config = load_config(config_path)
    if not (config.paths.mlruns / "mlflow.db").exists():
        return None

    from mlflow.tracking import MlflowClient

    mlflow_store.configure(config)
    return config, MlflowClient()


def _modellkarte_performance_rows() -> list[list[str]]:
    """The `## Performance gegen die einfache Grundrate` table's data rows (header
    dropped) -- `Modell | Log-Loss | Grundrate | Verbesserung | Run-ID`."""
    text = _read(MODELLKARTE)
    rows = _find_table(text, "Verbesserung")
    header, data_rows = rows[0], rows[1:]
    assert len(header) == 5, f"unexpected MODELLKARTE performance table header shape: {header}"
    return data_rows


def test_modellkarte_run_ids_resolve_to_registry_or_csv() -> None:
    doc_text = _read(MODELLKARTE)
    doc_run_ids = _run_ids_in_text(doc_text)
    if not doc_run_ids:
        pytest.skip("MODELLKARTE quotes no run ids -- nothing to resolve (e.g. no champion set)")

    csv_run_ids = set(_all_ablation_rows())
    live = _live_mlflow_client()

    unresolved = []
    for run_id in doc_run_ids:
        if run_id in csv_run_ids:
            continue
        if live is not None:
            _, client = live
            try:
                client.get_run(run_id)
                continue
            except Exception:  # noqa: BLE001 -- any MLflow lookup failure means "not found"
                pass
        unresolved.append(run_id)

    assert not unresolved, (
        f"{MODELLKARTE.name} quotes run id(s) resolving to neither a committed "
        f"ablation_summary.csv row nor the live MLflow registry: {unresolved}"
    )


def test_modellkarte_performance_figures_match_live_registry_or_csv() -> None:
    live = _live_mlflow_client()
    ablation_rows = _all_ablation_rows()
    data_rows = _modellkarte_performance_rows()

    if str(REPO_ROOT / "scripts") not in sys.path:
        sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import render_model_card as card  # noqa: E402

    checked = 0
    for cells in data_rows:
        model_cell, metric_cell, naive_cell, impr_cell, run_id_cell = cells
        run_id = run_id_cell.strip("`")
        if run_id == card.NA_NO_CHAMPION or not re.fullmatch(r"[0-9a-f]{32}", run_id):
            continue  # no champion set for this model -- nothing to figure-check

        if run_id in ablation_rows:
            csv_row = ablation_rows[run_id]
            _assert_figure_matches(metric_cell, float(csv_row["metric_value"]), f"{run_id} metric_value")
            _assert_figure_matches(naive_cell, float(csv_row["naive_value"]), f"{run_id} naive_value")
            _assert_figure_matches(
                impr_cell, float(csv_row["logloss_improvement"]), f"{run_id} logloss_improvement"
            )
            checked += 1
            continue

        if live is None:
            pytest.skip(
                f"run {run_id} has no committed ablation CSV row and no live MLflow store is "
                "available to verify it against (fresh checkout/CI -- mlruns/ is gitignored)"
            )
        _, client = live
        run = client.get_run(run_id)
        prefix = model_cell.strip("`").strip().lower()
        metric_name = card._POOLED_METRIC_NAME[prefix]
        naive_metric_name = f"naive_{metric_name.removeprefix('logo_')}"
        metric_value = run.data.metrics[metric_name]
        naive_value = run.data.metrics[naive_metric_name]
        improvement = run.data.metrics["logloss_improvement"]
        _assert_figure_matches(metric_cell, metric_value, f"{run_id} live {metric_name}")
        _assert_figure_matches(naive_cell, naive_value, f"{run_id} live {naive_metric_name}")
        _assert_figure_matches(impr_cell, improvement, f"{run_id} live logloss_improvement")
        checked += 1

    assert checked == len(data_rows), (
        f"expected {len(data_rows)} MODELLKARTE performance row(s) figure-checked, got {checked}"
    )


# ---------------------------------------------------------------------------
# PII gate
# ---------------------------------------------------------------------------


def test_no_roster_player_name_in_committed_docs() -> None:
    full_names, surnames = _load_roster_names()

    for path in (DOC, RUECKFRAGEN, MODELLKARTE):
        text = _read(path)
        lower = text.lower()
        for name in full_names:
            assert name.lower() not in lower, f"player name {name!r} found in {path}"
        for surname in surnames:
            pattern = re.compile(rf"\b{re.escape(surname)}\b", re.IGNORECASE)
            assert not pattern.search(text), f"surname {surname!r} found in {path}"


# ---------------------------------------------------------------------------
# docs/hc-rueckfragen-2026-09.md structural invariant (M3-3 compatibility)
# ---------------------------------------------------------------------------


def test_rueckfragen_frage_headings_stay_balanced() -> None:
    text = _read(RUECKFRAGEN)
    h2_frage = len(re.findall(r"^## Frage", text, re.MULTILINE))
    h3_frage = len(re.findall(r"^### Frage", text, re.MULTILINE))
    assert h2_frage == h3_frage, (
        f"unbalanced Frage headings: {h2_frage} '## Frage' vs {h3_frage} '### Frage' "
        "-- this must never change as a side effect of the Zusatzfragen addition"
    )


def test_rueckfragen_zusatzfrage_stub_count_matches_section() -> None:
    """Validates M3-2's own '## Zusatzfragen (M3-2, ...)' block specifically.

    Scoped to the M3-2 heading text (not '## Zusatzfragen' in general) since M3-4
    (`M3-04-07`) appends its own, differently-shaped '## Zusatzfragen (M3-4, Report)'
    section to the same file, using `#### Frage N` sub-headings rather than this
    block's `### Zusatzfrage <id>` convention -- a second, unrelated top-level
    section with a similar name is expected and does not indicate M3-2's own block
    was duplicated or corrupted.
    """
    text = _read(RUECKFRAGEN)

    section_headings = list(re.finditer(r"^## Zusatzfragen \(M3-2.*$", text, re.MULTILINE))
    assert len(section_headings) == 1, (
        f"expected exactly one '## Zusatzfragen (M3-2...)' section, found {len(section_headings)}"
    )
    heading = section_headings[0]
    body_start = heading.end()
    next_h2 = re.search(r"^## ", text[body_start:], re.MULTILINE)
    body_end = body_start + next_h2.start() if next_h2 else len(text)
    section_body = text[body_start:body_end]

    sub_questions_in_section = set(re.findall(r"^### Zusatzfrage (\S+)", section_body, re.MULTILINE))
    assert sub_questions_in_section, "## Zusatzfragen section has no ### Zusatzfrage sub-questions"

    total_zusatzfrage_headings = len(re.findall(r"^### Zusatzfrage", text, re.MULTILINE))
    assert total_zusatzfrage_headings == 2 * len(sub_questions_in_section), (
        f"expected {2 * len(sub_questions_in_section)} total '### Zusatzfrage' headings "
        f"(one in the question section, one stub under ## Antworten, per sub-question), "
        f"found {total_zusatzfrage_headings}"
    )


# ---------------------------------------------------------------------------
# Stand: line
# ---------------------------------------------------------------------------


def test_stand_line_is_a_valid_date() -> None:
    text = _read(DOC)
    match = re.search(r"Stand:\s*(\d{4}-\d{2}-\d{2})", text)
    assert match, f"{DOC.name} has no 'Stand: YYYY-MM-DD' line"
    date.fromisoformat(match.group(1))  # raises ValueError if not a real date
