"""Real, one-time migration of the existing MLflow tracking store into a new target store
(M3-05-09, ADR `docs/adr/0001-modell-plattform.md` Option (ii) gestaffelt, Punkt 1).

Uses only `mlflow`'s public `MlflowClient` / `mlflow.artifacts` API -- deliberately NOT the
third-party `mlflow-export-import` package, which has no RESEARCH package-legitimacy audit
and is unnecessary at this project's run count (a few dozen production runs, not thousands).

This script only ever *reads* from `--source` and only ever *writes* to `--target`: the
source store is never modified, deleted, or locked. That non-destructiveness is itself the
rollback path for the registry side of this migration -- stop pointing `ffep` at the target
(unset `MLFLOW_TRACKING_URI`) and the source store is exactly as it was before this script
ran, verified by `test_migrate_source_run_and_param_counts_unchanged_after_migrate`.

Usage:
    uv run python scripts/migrate_mlflow_store.py \\
        --source "sqlite:///$(pwd)/mlruns/mlflow.db" \\
        --target "http://127.0.0.1:5000"
"""

from __future__ import annotations

import argparse
import json
import tempfile
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path

import mlflow.artifacts
from mlflow import MlflowClient
from mlflow.entities import Metric, Param

# Per docs/model-training.md section 4's existing candidate-experiment naming
# (`{ep,wp}_model_candidates`, `model.experiments.CANDIDATE_EXPERIMENT_SUFFIX`).
DEFAULT_EXPERIMENT_NAMES: tuple[str, ...] = (
    "ep_model",
    "wp_model",
    "ep_model_candidates",
    "wp_model_candidates",
)
DEFAULT_MODEL_NAMES: tuple[str, ...] = ("ep_model", "wp_model")
CHAMPION_ALIAS = "champion"

# Internal MLflow tags are regenerated by the target store on write -- copying them verbatim
# would either be rejected or would misrepresent the target run's own provenance.
_INTERNAL_TAG_PREFIX = "mlflow."

# Tag written on every migrated target run, carrying the source run id it was copied from.
# **Why this exists (a verified correction to this plan's own literal wording):** MLflow's
# `MlflowClient.create_run`/backend stores (verified against SqlAlchemyStore.create_run this
# session) always generate their own fresh `run_id` (`uuid.uuid4().hex`) -- there is no public
# API to force a specific run id onto a newly created run in a different store. This matches
# the ADR's own stated caveat (`docs/adr/0001-modell-plattform.md` A.2: "MLflow keine
# offiziell unterstützte SQLite-zu-Postgres-Migrationsfunktion mitbringt"). A migrated run
# therefore always gets a NEW run id in the target store -- this tag is the migration's actual
# provenance/fidelity proof (source run id -> target run id, auditable per run), used in place
# of literal run-id equality wherever this script's docstrings/tests discuss "faithful"
# migration. See `docs/mlflow-container-platform.md`'s migration section for the operator-
# facing explanation.
MIGRATED_FROM_RUN_ID_TAG = "migrated_from_run_id"


class MigrationError(RuntimeError):
    """Raised for every failure mode in this script -- a missing expected artifact, a run
    that cannot be recreated on the target, or a champion alias that cannot be resolved.
    Follows this codebase's no-silent-failure, named-exception convention (see
    `flag_football_ep.model.registry.RegistryError`).
    """


@dataclass
class MigrationReport:
    """Counts of what actually moved, plus the resolved champion run id per model -- written
    to a JSON report file by `main()` so a migration run leaves an auditable artifact, not
    just log lines.
    """

    source_uri: str
    target_uri: str
    experiment_run_counts: dict[str, int] = field(default_factory=dict)
    skipped_experiments: list[str] = field(default_factory=list)
    model_version_counts: dict[str, int] = field(default_factory=dict)
    champion_run_ids: dict[str, str] = field(default_factory=dict)
    skipped_models: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


def _non_internal_tags(tags: dict[str, str]) -> dict[str, str]:
    return {k: v for k, v in tags.items() if not k.startswith(_INTERNAL_TAG_PREFIX)}


def _copy_run(
    source_client: MlflowClient,
    target_client: MlflowClient,
    source_run,
    target_experiment_id: str,
    source_uri: str,
) -> str:
    """Copy one run's params/metrics/tags/artifacts into a new run under
    `target_experiment_id`. Returns the new target run id.

    The target run always gets a fresh, server-generated run id (see
    `MIGRATED_FROM_RUN_ID_TAG` above) -- the returned/created run additionally carries a
    `migrated_from_run_id` tag naming the exact source run it was copied from, so the mapping
    is auditable even though the id itself necessarily changed.
    """
    tags = _non_internal_tags(source_run.data.tags)
    tags[MIGRATED_FROM_RUN_ID_TAG] = source_run.info.run_id
    target_run = target_client.create_run(
        experiment_id=target_experiment_id,
        run_name=source_run.info.run_name,
        tags=tags,
    )
    target_run_id = target_run.info.run_id

    params = [Param(k, v) for k, v in source_run.data.params.items()]
    metrics = [
        Metric(k, v, source_run.info.end_time or source_run.info.start_time, 0)
        for k, v in source_run.data.metrics.items()
    ]
    if params or metrics:
        target_client.log_batch(target_run_id, metrics=metrics, params=params)

    # Artifact tree: download everything from the source run, then re-upload to the target
    # run's own artifact root. Raise loudly (never silently skip) when the source lists
    # artifacts but the download comes back empty -- a partial/missing artifact tree would
    # silently produce a broken target registry (T-M3-05-21).
    source_artifacts = source_client.list_artifacts(source_run.info.run_id)
    if source_artifacts:
        with tempfile.TemporaryDirectory() as tmp_dir:
            local_dir = mlflow.artifacts.download_artifacts(
                run_id=source_run.info.run_id,
                dst_path=tmp_dir,
                tracking_uri=source_uri,
            )
            downloaded_files = list(Path(local_dir).rglob("*"))
            if not any(p.is_file() for p in downloaded_files):
                raise MigrationError(
                    f"source run {source_run.info.run_id!r} lists "
                    f"{len(source_artifacts)} artifact entries but downloading them "
                    f"produced no files under {local_dir!r} -- refusing to silently "
                    "register a target run with a missing artifact tree"
                )
            target_client.log_artifacts(target_run_id, local_dir)

    # RunInfo.status is a plain terminal-state string ("FINISHED"/"FAILED"/"KILLED") for any
    # completed run; anything else (e.g. a still-RUNNING source run) is normalized to
    # FINISHED, the only sensible terminal state for a migrated copy.
    final_status = source_run.info.status
    if final_status not in {"FINISHED", "FAILED", "KILLED"}:
        final_status = "FINISHED"
    target_client.set_terminated(
        target_run_id, status=final_status, end_time=source_run.info.end_time
    )
    return target_run_id


def _migrate_experiment(
    source_client: MlflowClient,
    target_client: MlflowClient,
    name: str,
    source_uri: str,
    report: MigrationReport,
) -> dict[str, str]:
    """Migrate every run of experiment `name`. Returns the source-run-id -> target-run-id map
    for this experiment (empty if the experiment does not exist in source -- logged as
    skipped, never an error, matching this plan's stated "skip any name absent from source,
    log which").
    """
    source_experiment = source_client.get_experiment_by_name(name)
    if source_experiment is None:
        report.skipped_experiments.append(name)
        return {}

    target_experiment = target_client.get_experiment_by_name(name)
    target_experiment_id = (
        target_experiment.experiment_id
        if target_experiment is not None
        else target_client.create_experiment(name)
    )

    source_runs = source_client.search_runs(
        [source_experiment.experiment_id],
        max_results=50_000,
        order_by=["attribute.start_time ASC"],
    )
    run_id_map: dict[str, str] = {}
    for source_run in source_runs:
        target_run_id = _copy_run(
            source_client, target_client, source_run, target_experiment_id, source_uri
        )
        run_id_map[source_run.info.run_id] = target_run_id

    report.experiment_run_counts[name] = len(source_runs)
    return run_id_map


def _migrate_model(
    source_client: MlflowClient,
    target_client: MlflowClient,
    name: str,
    run_id_map: dict[str, str],
    report: MigrationReport,
) -> None:
    """Migrate every registered version of model `name`, in ascending version order, then
    move the target `champion` alias to whichever target version corresponds to the source
    run currently aliased `champion`. Skipped (logged, not an error) if `name` has no
    registered versions in source.
    """
    source_versions = sorted(
        source_client.search_model_versions(f"name='{name}'"), key=lambda mv: int(mv.version)
    )
    if not source_versions:
        report.skipped_models.append(name)
        return

    try:
        target_client.get_registered_model(name)
    except Exception:  # noqa: BLE001 -- MlflowException on "not found", version-dependent
        target_client.create_registered_model(name)

    source_to_target_version: dict[str, str] = {}
    for mv in source_versions:
        target_run_id = run_id_map.get(mv.run_id)
        if target_run_id is None:
            raise MigrationError(
                f"registered model {name!r} version {mv.version!r} references source run "
                f"{mv.run_id!r}, which was not migrated (not found in the run-id map built "
                f"from experiment migration) -- refusing to register a target version "
                "pointing at a run that does not exist on the target store"
            )
        new_version = target_client.create_model_version(
            name=name,
            source=f"runs:/{target_run_id}/model",
            run_id=target_run_id,
        )
        source_to_target_version[mv.version] = new_version.version

    report.model_version_counts[name] = len(source_versions)

    try:
        champion_source_mv = source_client.get_model_version_by_alias(name, CHAMPION_ALIAS)
    except Exception:  # noqa: BLE001 -- no champion alias set in source, nothing to move
        return

    target_champion_version = source_to_target_version[champion_source_mv.version]
    target_client.set_registered_model_alias(name, CHAMPION_ALIAS, target_champion_version)
    target_champion_mv = target_client.get_model_version_by_alias(name, CHAMPION_ALIAS)
    report.champion_run_ids[name] = target_champion_mv.run_id


def migrate(
    source_uri: str,
    target_uri: str,
    experiment_names: tuple[str, ...] = DEFAULT_EXPERIMENT_NAMES,
    model_names: tuple[str, ...] = DEFAULT_MODEL_NAMES,
) -> MigrationReport:
    """Copy every run in each named source experiment into an identically-named target
    experiment (params, metrics, non-internal tags, full artifact tree), then re-register
    every version of each named model against the target store in ascending version order
    and move the target `champion` alias to match source. Read-only against `source_uri`.
    """
    source_client = MlflowClient(tracking_uri=source_uri)
    target_client = MlflowClient(tracking_uri=target_uri)
    report = MigrationReport(source_uri=source_uri, target_uri=target_uri)

    combined_run_id_map: dict[str, str] = {}
    for name in experiment_names:
        run_id_map = _migrate_experiment(source_client, target_client, name, source_uri, report)
        combined_run_id_map.update(run_id_map)

    for name in model_names:
        _migrate_model(source_client, target_client, name, combined_run_id_map, report)

    return report


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, help="Source MLflow tracking URI (read-only)")
    parser.add_argument("--target", required=True, help="Target MLflow tracking URI (write)")
    parser.add_argument(
        "--experiments",
        default=None,
        help="Comma-separated experiment names to migrate (default: %r)"
        % (",".join(DEFAULT_EXPERIMENT_NAMES),),
    )
    parser.add_argument(
        "--report",
        default=None,
        help="Path to write the JSON MigrationReport (default: "
        "backups/mlflow/migration_report_<UTC-date>.json)",
    )
    return parser


def main(argv: list[str] | None = None) -> MigrationReport:
    args = _build_arg_parser().parse_args(argv)
    experiment_names = (
        tuple(name.strip() for name in args.experiments.split(","))
        if args.experiments
        else DEFAULT_EXPERIMENT_NAMES
    )
    report = migrate(args.source, args.target, experiment_names=experiment_names)

    report_path = Path(
        args.report
        or f"backups/mlflow/migration_report_{datetime.now(UTC):%Y-%m-%d}.json"
    )
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report.to_dict(), indent=2, sort_keys=True) + "\n")
    print(f"migration report written to {report_path}")
    print(json.dumps(report.to_dict(), indent=2, sort_keys=True))
    return report


if __name__ == "__main__":
    main()
